project_id = "kgtrlsmhqtnwynpjnpnm"

[functions.continuous-sync-binance]
verify_jwt = false

[functions.recalculate-strategy-hashes]
verify_jwt = false

[functions.sync-funding-fees]
verify_jwt = false

[functions.backfill-mae]
verify_jwt = false

[functions.continuous-scan-quant]
verify_jwt = false

[functions.scanner-keepalive]
verify_jwt = false

[functions.reconcile-trade-fees]
verify_jwt = false
