-- Add adaptive ATR and ADX fields to indicator_config table
ALTER TABLE indicator_config
ADD COLUMN IF NOT EXISTS atr_base_min NUMERIC DEFAULT 0.4,
ADD COLUMN IF NOT EXISTS atr_floor NUMERIC DEFAULT 0.2,
ADD COLUMN IF NOT EXISTS atr_ceiling NUMERIC DEFAULT 1.0,
ADD COLUMN IF NOT EXISTS adx_base_min NUMERIC DEFAULT 30,
ADD COLUMN IF NOT EXISTS adx_floor NUMERIC DEFAULT 20,
ADD COLUMN IF NOT EXISTS adx_ceiling NUMERIC DEFAULT 50;