UPDATE indicator_config SET
  name = 'Bedste Hybrid Strategi (Endelig Version)',
  enabled = true,
  ema_enabled = true, ema_fast = 9, ema_medium = 21, ema_slow = 200, ema_medium_trend = 50,
  ema_hard_filter = true, ema_trend_hard_filter = true, min_ema_spread_percent = 0.15,
  rsi_enabled = true, rsi_period = 14, rsi_min_long = 40, rsi_max_short = 60, rsi_zone_width = 10,
  rsi_momentum_periods = 3, rsi_hard_filter = false,
  stochrsi_enabled = true, stochrsi_period = 14, stochrsi_k_period = 3, stochrsi_d_period = 3,
  stochrsi_hard_filter = true, stochrsi_short_mode = 'REVERSAL_ROLLOVER', stochrsi_long_mode = 'CLASSIC',
  rollover_d_min_short = 70, stochrsi_overbought_k = 96, stochrsi_overbought_d = 94,
  stochrsi_oversold_k = 4, stochrsi_oversold_d = 6,
  macd_enabled = true, macd_fast = 12, macd_slow = 26, macd_signal = 9,
  macd_histogram_threshold = 0.0001, macd_hard_filter = false, macd_direction_enabled = true,
  macd_color_change_hard_filter = true, histogram_momentum_enabled = true, histogram_momentum_periods = 2,
  bb_enabled = true, bb_period = 20, bb_std_dev = 2.5, bb_hard_filter = false,
  atr_enabled = true, atr_period = 14, atr_hard_filter = true, min_atr_percent = 0.25,
  atr_stop_loss_multiplier = 3, atr_trailing_stop_multiplier = 2.5,
  trailing_stop_activation_enabled = true, trailing_stop_activation_atr = 1.5,
  adaptive_atr_enabled = true, atr_base_min = 0.3, atr_floor = 0.15, atr_ceiling = 0.6,
  adx_enabled = true, adx_period = 14, adx_threshold = 0, adx_hard_filter = true,
  adx_floor = 0, adx_ceiling = 30, adaptive_adx_enabled = true, adx_base_min = 25,
  volume_enabled = true, volume_hard_filter = true, volume_multiplier = 1.8, volume_avg_period = 20,
  volume_mode_short = 'HARD', volume_multiplier_short = 1.8,
  pivot_points_enabled = true, pivot_points_hard_filter = false, pivot_points_timeframe = '1d',
  pivot_points_lookback = 15, pivot_points_near_threshold = 0.5,
  higher_trend_enabled = true, higher_trend_hard_filter = true, higher_trend_timeframe = '4h',
  signal_conditions_required = 4,
  scan_interval = '1h', trend_timeframe = '4h', trend_timeframe_enabled = true, klines_limit = 300,
  break_even_enabled = true, break_even_ratchet_only = true, break_even_atr_enabled = false,
  break_even_profit_pct_enabled = true, break_even_profit_pct_trigger = 1.2,
  break_even_profit_pct_stop_over_entry = 0.3,
  peak_lock_enabled = true, peak_lock_activate_profit_pct = 2, peak_lock_distance_pct = 1,
  peak_lock_min_profit_floor_pct = 0.6, peak_lock_ratchet_only = true,
  max_sl_after_mfe_enabled = true, max_sl_after_mfe_pct = 1.8, max_sl_after_mfe_max_dist_pct = 1.2,
  hard_sl_pct_enabled = true, hard_sl_pct = 1.8,
  position_size_percent = 8, risk_per_trade_percent = 0.5, max_open_positions = 2,
  max_exposure_percent = 60, daily_loss_limit_percent = 3, leverage = 3,
  auto_exit_enabled = true, max_position_duration_minutes = 600, conditional_time_exit_enabled = true,
  regime_router_enabled = true, regime_method = 'ADX_ATR', regime_operator = 'AND',
  regime_adx_threshold = 28, regime_atr_pct_threshold = 0.4, regime_lock_at_entry = true,
  regime_if_true = 'TREND', regime_if_false = 'RANGE',
  regime_trend_exit_profile_id = '93bd4a80-cb00-4877-ad52-75a8deb9e913',
  regime_range_exit_profile_id = 'e757965a-cd75-4ba2-a55c-93137b17ccf9',
  supertrend_enabled = false, obv_enabled = false, cci_enabled = false, psar_enabled = false,
  updated_at = now()
WHERE id = '3edbae12-bfe4-4430-a61a-eab16e648437';